#define min(a,b) ((a<b)?a:b)
#define max(a,b) ((a>b)?a:b)
#define pips_min_2(a,b) min(a,b)
#define pips_max_2(a,b) max(a,b)
#define pips_min_3(a,b,c) min(pips_min_2(a,b),c)
#define pips_max_3(a,b,c) max(pips_max_2(a,b),c)
#define pips_min_4(a,b,c,d) min(pips_min_3(a,b,c),d)
#define pips_max_4(a,b,c,d) max(pips_max_3(a,b,c),d)
#define pips_min_5(a,b,c,d,e ) min( pips_min_4(a,b,c,d),e)
#define pips_max_5(a,b,c,d,e) max(pips_max_4(a,b,c,d),e)
#define pips_min_6(a,b,c,d,e,f) min( pips_min_5(a,b,c,d,e ),f)
#define pips_max_6(a,b,c,d,e,f) max( pips_max_5(a,b,c,d,e),f)
#define pips_min_7(a,b,c,d,e,f,g) min(pips_min_6(a,b,c,d,e,f),g)
#define pips_max_7(a,b,c,d,e,f,g) max(pips_max_6(a,b,c,d,e,f),g)
#define pips_min_8(a,b,c,d,e,f,g,h) min(pips_min_7(a,b,c,d,e,f,g),h)
#define pips_max_8(a,b,c,d,e,f,g,h) max(pips_max_7(a,b,c,d,e,f,g),h)
#define pips_min_9(a,b,c,d,e,f,g,h,i) min(pips_min_8(a,b,c,d,e,f,g,h),i)
#define pips_max_9(a,b,c,d,e,f,g,h,i) max(pips_max_8(a,b,c,d,e,f,g,h),i)
#define pips_min_10(a,b,c,d,e,f,g,h,i, j) min( pips_min_9(a,b,c,d,e,f,g,h,i),j)
#define pips_max_10(a,b,c,d,e,f,g,h,i, j) max( pips_max_9(a,b,c,d,e,f,g,h,i),j)
