dist: xenial
language: python
matrix:
  include:
    - python: 3.7
      env: PYLINT=2.3
os: linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pylint=$PYLINT
  - source activate test-environment
  - pip install -r requirements.txt

script: python3 create_kernels_with_deps.py